In [22]:
import json
import requests
import pandas as pd

headers = {
    'x-rapidapi-host': "v3.football.api-sports.io",
    'x-rapidapi-key': "063a86c9f9ff41c06288c479fae7e244"
    }

r = requests.get('https://v3.football.api-sports.io/fixtures?season=2015&league=135', headers=headers)
test = requests.get('https://v3.football.api-sports.io/fixtures/statistics?fixture=192297', headers=headers)

In [23]:
number_responses = r.json()['results']

In [24]:
d = []
for i in range(number_responses):
    d.append(
        {
            'date': r.json()['response'][i]['fixture']['date'],
            'fixture_id': r.json()['response'][i]['fixture']['id'],
            'home_team':  r.json()['response'][i]['teams']['home']['name'],
            'away_team': r.json()['response'][i]['teams']['away']['name'],
            'home_goals': r.json()['response'][i]['goals']['home'],
            'away_goals': r.json()['response'][i]['goals']['away'],
        }
    )

data_2015 = pd.DataFrame(d)
data_2015.set_index('date', inplace=True)

In [25]:
data_2015

,fixture_id,home_team,away_team,home_goals,away_goals
date,,,,,
2015-08-22T16:00:00+00:00,196403,Verona,AS Roma,1,1
2015-08-22T18:45:00+00:00,196404,Lazio,Bologna,2,1
2015-08-23T16:00:00+00:00,196405,Juventus,Udinese,0,1
2015-08-23T18:45:00+00:00,196406,Empoli,Chievo,1,3
2015-08-23T18:45:00+00:00,196407,Fiorentina,AC Milan,2,0
...,...,...,...,...,...
2016-05-15T16:00:00+00:00,196778,Chievo,Bologna,0,0
2016-05-15T16:00:00+00:00,196779,Empoli,Torino,2,1
2016-05-15T18:45:00+00:00,196780,Udinese,Carpi,1,2
2016-05-15T18:45:00+00:00,196781,Lazio,Fiorentina,2,4
2016-05-15T18:45:00+00:00,196782,Palermo,Verona,3,2

In [29]:
home_shots_on_goal = []
for i in data_2015['fixture_id']:
    stats = requests.get(f"https://v3.football.api-sports.io/fixtures/statistics?fixture={i}", headers=headers)
    if stats.json()['response'][0]['statistics'][0]['value'] == "null":
        home_shot_on_goal.append(0)
        else:
            home_shots_on_goal.append(stats.json()['response'][0]['statistics'][0]['value'])
    
data_2015['home_shots_on_goal'] = home_shots_on_goal

In [30]:
data_2015

,fixture_id,home_team,away_team,home_goals,away_goals,home_shots_on_goal
date,,,,,,
2015-08-22T16:00:00+00:00,196403,Verona,AS Roma,1,1,7.0
2015-08-22T18:45:00+00:00,196404,Lazio,Bologna,2,1,9.0
2015-08-23T16:00:00+00:00,196405,Juventus,Udinese,0,1,5.0
2015-08-23T18:45:00+00:00,196406,Empoli,Chievo,1,3,4.0
2015-08-23T18:45:00+00:00,196407,Fiorentina,AC Milan,2,0,7.0
...,...,...,...,...,...,...
2016-05-15T16:00:00+00:00,196778,Chievo,Bologna,0,0,NaN
2016-05-15T16:00:00+00:00,196779,Empoli,Torino,2,1,3.0
2016-05-15T18:45:00+00:00,196780,Udinese,Carpi,1,2,5.0
2016-05-15T18:45:00+00:00,196781,Lazio,Fiorentina,2,4,6.0
2016-05-15T18:45:00+00:00,196782,Palermo,Verona,3,2,3.0

In [ ]:
data_2010